name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push backend image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/nestmate-backend:latest
          ${{ secrets.DOCKER_USERNAME }}/nestmate-backend:${{ github.sha }}
    
    - name: Build and push web image
      uses: docker/build-push-action@v5
      with:
        context: ./web
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/nestmate-web:latest
          ${{ secrets.DOCKER_USERNAME }}/nestmate-web:${{ github.sha }}
    
    # Add deployment steps here (e.g., deploy to cloud provider)
    - name: Deploy to production
      run: |
        echo "Deployment steps would go here"
        echo "This could include:"
        echo "- Deploying to Kubernetes"
        echo "- Updating cloud services"
        echo "- Running database migrations"
        echo "- Updating environment variables"